apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw1-deployment
  namespace: hw2
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: surveyform
  template:
    metadata:
      labels:
        app: surveyform
    spec:
      containers:
      - name: surveyform
        image: hemu1999/surveyform:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hw1-service
  namespace: hw2
spec:
  selector:
    app: surveyform
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30091
  type: NodePort
