apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw2-deployment
  namespace: hw2
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: surveyform
  template:
    metadata:
      labels:
        app: surveyform
    spec:
      containers:
      - name: surveyform
        image: hemu1999/surveyform:latest
        ports:
        - containerPort: 80
