apiVersion: v1
kind: Service
metadata:
  name: hw2-service
  namespace: hw2
spec:
  selector:
    app: surveyform
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30091
  type: NodePort
  externalIPs:
    - 192.168.49.2